version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-atlas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-atlas}
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - atlas-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    ports:
      - 1411:1411
    volumes:
      - "./data:/app/data"
    environment:
      - TRUST_PROXY=${TRUST_PROXY}
      - APP_URL=${APP_URL}
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  atlas-web:
    image: ghcr.io/panchitovdv/atlas-web:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ATLAS_API_URL=${ATLAS_API_URL}
      - ATLAS_API_KEY=${ATLAS_API_KEY}
      - IDENTITY_CLIENT_ID=${IDENTITY_CLIENT_ID}
      - IDENTITY_CLIENT_SECRET=${IDENTITY_CLIENT_SECRET}
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_ATLAS_WEBSOCKET_URL=${VITE_ATLAS_WEBSOCKET_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    depends_on:
      db:
        condition: service_healthy
    #env_file:
     # - .env
    networks:
      - atlas-net

networks:
  atlas-net:
    driver: bridge
